### PR TITLE
Issue 2379: Make it possible to select text in posts.

### PR DESCRIPTION
**Pull request by Gryzor**
### Objective
* Allow the user to use native Android gestures (long press-drag) to start selecting text.
* Remove conflicting listeners that prevent users from selecting text.

### Issue
* #2379 

### Description
* As simple as it sounds, setting `textIsSelectable` to `true` in the XML should be enough, but in some complex layouts and hierarchies, other gestures may be taking precedence and prevent this from happening.
* This is my 1st PR and I am very new to this codebase, so please _let me know if I am missing something_, as it took me a bit to figure out which view Holders were being used where/when. So I may have modified one that I didn't need to, or missed one altogether.
* The LongPress click listener in the ThreadView has been _removed_ from the content. Although I think it's a nice to have feature, if the need to select text manually is preferred (this PR) then the long press would conflict (and take precedence), making it impossible for users to manually select text. Please let me know if this is ok.

### Known issues
* I haven't been able to make it _reliably_ work in the "main/home" list, because of the conflict of gestures (I believe Android is having hard time deciding where the gesture goes). On one hand there's the Drawer which takes swipe to the right, then there's the TabLayouts/ViewPager with the different tabs, this occupies the swipe to the left gesture; then there's the actual recyclerView with a SwipeToRefresh layout, driving swipe up/down gestures, so all four directions are taken. On Android, long press and drag over text is how you initiate the selection mechanism, so naturally this conflicts with the above more often than not.
That being said, it *does work* sometimes, so any pointers or ideas are appreciated.
I believe that even then, as a workaround, users can always tap the post, and manually copy in the Thread view, where it works all the time.

### Tested
* OnePlus 6p / Android 11
* Samsung S20 / Android 12

### CODE REVIEW

**Comment by connyduck** [comment]
Please only change the detailed status, I think it is enough if there is one place to copy the content.

Also, I would remove the long press listener and the copy_to_clipboard_success string entirely, having multiple ways to copy is not necessary.

**Comment by connyduck** [comment]
Please also remove the now unused string. It should be enough to remove it from the default translation, Weblate will send a PR to remove it from the others, but you can also do all 45 translations.
But the rest looks good!

**Comment by Gryzor** [comment]
@connyduck done, did all translations as it was easy to do. Had to solve a merge conflict but it was just a coincidence that the string above changed in that locale `hu`. /shrug

**Review by connyduck — APPROVED** [review]

**Comment by joenepraat** [comment]
Great! So now we can just copy a word or a sentence, search that string in e.g. Wikipedia and a translate app. Thanks!

**Pull request merged**
