### PR TITLE
Add pinned status tab

### PR DESCRIPTION
**Pull request by kyori19**
Related to #443.

I added new tab "pinned" to AccountActivity, which shows user's pinned toot.

### CODE REVIEW

**Comment by charlag** [comment]
Wow, that's an interesting idea, I've never thought about that possibility, always thought we would need to change timeline.
The problem is that "pinned" loses some sense in this case because it's hidden by default but it's certainly better than nothing IMO.

**Comment by connyduck** [comment]
Its definitely better than nothing but I still think we should change it later so the pinned toots are shown above the other toots on the first tab.

**Comment by kyori19** [comment]
Actually , I had another idea to show pinned toots above normal toots.
https://github.com/accelforce/Tusky/commit/1ab0aef2c0bed9f8bffce02490ee62ec406d66f4
But this method causes many problems so I gave up this idea.

**Comment by connyduck** [comment]
Can you switch the `TabLayout` in `activity_account.xml` to `app:tabMode="scrollable"`? It makes the tabs look way better on small screens

**Comment by kyori19** [comment]
@connyduck OK, I changed fixed to scrollable.

**Pull request merged**
