### PR TITLE
Apply conversation filters to threads. Addresses #1349

### PR DESCRIPTION
**Pull request by Tak**
- Extract most of the filtering logic into `SFragment`
- Provide specialized overrides in `TimelineFragment` and `ViewThreadFragment`

### CODE REVIEW

**Comment by connyduck** [comment]
Awesome! I just wonder if we maybe should cache the filters somehow so they are not reloaded every time an thread is viewed (does not have to be in this PR)

**Comment by Tak** [comment]
Makes sense, we just need to decide whether/how to invalidate them in that case

**Comment by connyduck** [comment]
What about invalidating them when they are changed in the app, and reload when they app is started or accounts are switched? Should be fine for most usecases, users that change filters in another client hopefully think about restarting the app.

**Comment by Tak** [comment]
Ok, now the filters are cached globally unless modified locally

**Comment by connyduck** [comment]
Nice! Now you just need to clear the filter cache when accounts are changed in the app.

**Comment by Tak** [comment]
🤦‍♂

**Comment by Tak** [comment]
Ok, account switching should be covered now :smiley:

**Comment by connyduck** [comment]
awesome, thx!

**Pull request merged**
