### PR TITLE
Be explicit about the `firstStrong` text direction on UGC

### PR DESCRIPTION
**Pull request by nikclayton**
`activity_account` sets the root text direction to `anyRtl`.

This is OK for UI elements, but can be a problem for user generated content (UGC) that may contain bidirectional text.

Fix this by explicitly restoring the default behaviour, `firstStrong`, on views in `activity_account` that can show UGC.

Fixes https://github.com/tuskyapp/Tusky/issues/3294

### CODE REVIEW

**Comment by nikclayton** [comment]
I think this is correct (my analysis is in the linked PR, with links to other PRs that have dealt with this), but someone more knowledgeable than me about bidi text handling should take a look.

If you want to compare before/after, my profile bio (@nikclayton@mastodon.social) currently contains a mix of LTR and RTL text that did not render correctly before this PR, and now renders correctly with it.

**Comment by Lakoja** [comment]
Also status are user-generated content.

So to be consistent with the Mastodon Web gui it should (at least) also be set for item_conversation.xml#status_content and item_status.xml#status_content.

(Note: In the Web gui it doesn't work for the username. The display of that seems to be a bit random: different in text field than actual display.)

Generally I wonder if it is possible to set an application-wide default for textDirection. (I'd expect a consistent behavior for _everything_, I guess.)

**Comment by Lakoja** [comment]
Maybe it would also be sensible to remove the (3) text directions "any rtl" for a few activities.

**Comment by nikclayton** [comment]
@Lakoja I don't think that's necessary, per https://github.com/tuskyapp/Tusky/issues/3294#issuecomment-1434681929. To summarise:

1. The Android default is `firstStrong`. This is why `item_conversation` and `item_status` work correctly before this PR.
2. This was overridden for some wrapper views in `activity_account.xml` in https://github.com/tuskyapp/Tusky/pull/964 (the discussion in the PR has screenshots showing why `anyRTL` makes sense in a few places)
3. This PR restores the default for some children of the wrapper views that were unintentionally affected by the change in (2)

**Comment by nikclayton** [comment]
I checked this against the profile of https://mastodon.social/@nasser@merveilles.town who runs https://notarabic.com.

Without this PR the "pronouns" section of his account profile **does not** display correctly, appearing as "هو/he/him/".

This is (a) different from the web UI (which shows "he/him/هو") and (b) is also different from what you get if you copy that text out of Tusky and paste it in to an app which does handle this correctly. Tusky is showing the Arabic text in the wrong place (on the left) and has the spare "/" on the right.

So I'm now confident that this is the correct fix.

**Pull request merged**
