### PR TITLE
Update zh-rTW translation

### PR DESCRIPTION
**Pull request by pellaeon**

### CODE REVIEW

**Comment by connyduck** [comment]
@aka-rin can you check this, please?

**Comment by aka-rin** [comment]
@connyduck OK, just merge it ...

FYI, I forgot to translate a string:

```html
<string name="pref_default_media_sensitivity">Always mark media as sensitive</string>
```

It would be better if you add it up. @pellaeon 

PS: You can also replace the zh-HK and zh-MO translations ...

**Comment by connyduck** [comment]
@pellaeon can you integrate the changes suggested by aka-rin please?

**Comment by pellaeon** [comment]
Done, sorry for the delay.

**Comment by connyduck** [comment]
What about zh-HK and zh-MO? They are just copies of zh-TW

**Comment by pellaeon** [comment]
Copied them over.

**Comment by connyduck** [comment]
awesome, thx!

**Pull request merged**
