### PR TITLE
Updated sv (Swedish) translation

### PR DESCRIPTION
**Pull request by iah**
First 60% done in [Stringlate](https://lonamiwebs.github.io/stringlate/).

### CODE REVIEW

**Comment by charlag** [comment]
Hi!
Thanks for the translation. Is it ready to merge?

**Comment by iah** [comment]
Sure, but as said. It's only 60% done. I'll have more soon.

**Comment by charlag** [comment]
We're not releasing anything right now so I'll wait for the release if you plan to do more.

**Comment by iah** [comment]
Yeah, sounds sane. I'll keep you posted.

**Pull request closed without merging**
