### PR TITLE
Fix conversations

### PR DESCRIPTION
**Pull request by connyduck**
This fixes several problems with conversations (the code is basically just taken over from the newer timeline code)

- timestamps now update on pull-to-refresh
- the view now jumps up a bit to reveal newly loaded items after pull-to-refresh
- "nothing here" shown when conversations are empty instead of nothing
- when replying from conversations, the "replying to" field will be correctly filled
- the "fabHide" setting is now respected in the ConversationsFragment as well
- and most importantly, pagination now works as expected

kind of a prerequisite to https://github.com/tuskyapp/Tusky/issues/2552

I'd like to merge this at the same time as https://github.com/tuskyapp/Tusky/pull/2549 because the migrations overlap

### CODE REVIEW

**Comment by connyduck** [comment]
draft because some details still aren't perfect

**Comment by connyduck** [comment]
While this is a hundred times better than before, there are still 2 glitches:
- When the database is empty and conversations load for the first time, the list does not start at the top and one has to scroll up. I think is because of the load state footer that is shown and the recyclerview trying to keep the position. No idea how to turn this behavior off, I tried a lot.
- When having a long list of conversations and being way down, suddenly jumping up shows the wrong views for a split second. This is because paging from database does not hold all data in memory. We have the same behavior in timelines.

**Review by charlag — COMMENTED** [review]
I'm a not so confident with all the paging APIs but maybe it's worth leaving a comment on how/why `order` works? I don't understand it fully, does server not reorder them all the time?

**Comment by connyduck** [comment]
> I'm a not so confident with all the paging APIs but maybe it's worth leaving a comment on how/why order works? I don't understand it fully, does server not reorder them all the time?

Yes it does reorder it all the time but I also reload it all the time. After a pull to refresh there is only the current page in the cache.

**Pull request merged**
