### PR TITLE
Load sensitive media previews for only when shown

### PR DESCRIPTION
**Pull request by charlag**
Couldn't find an issue for that but I remember that we've discussed this.
Lazily load sensitive media: don't load it until shown.

### CODE REVIEW

**Comment by charlag** [comment]
Oooops. I'll have a look. Does it happen consistently with this post?

**Comment by connyduck** [comment]
Yes, but it is also somehow related to view recycling. On app start its fine, then I scroll down and up again, then its gone, then its there again, and so on.

**Comment by charlag** [comment]
Is this media sensitive?

**Comment by connyduck** [comment]
yes

**Comment by charlag** [comment]
Fixed! Should work now. That was pretty :man_facepalming:

**Pull request merged**
