### PR TITLE
Add system black theme

### LINKED ISSUE #1222: Allow auto-switch theme to black from light

### PR DESCRIPTION
**Pull request by Mylloon**
Close #1222

### CODE REVIEW

**Review by Tak — APPROVED** [review]
Looks good to me ( % lint fixes)

**Comment by Mylloon** [comment]
I hope all the linting issues are fixed

**Comment by Tak** [comment]
Yeah, the remaining failure looks like an infrastructure issue

**Comment by Tak** [comment]
Hi @Mylloon - If you can merge `develop` and resolve the conflicts, we'll merge this. Thanks!

**Comment by Mylloon** [comment]
Oh, I think I messed something up

**Pull request merged**
