### PR TITLE
Improve french translation

### PR DESCRIPTION
**Pull request by BoFFire**
Improve french translation and push 100% translated.

### CODE REVIEW

**Comment by BoFFire** [comment]
Humm, may be formatting problem ?

**Comment by charlag** [comment]
I formatted, squashed and merged it but somehow screwed up id hash I guess go GitHub didn't pick it up.

**Comment by BoFFire** [comment]
humm should I check something ?

**Comment by charlag** [comment]
No, it's in, it's my screwup, git didn't close the issue automatically but remembers that you've made a change, so it shouldn't be a problem I guess

**Pull request closed without merging**
