### PR TITLE
Add titel, description and images for fastlane (and F-Droid)

### PR DESCRIPTION
**Pull request by jaller94**
This is mainly to add screenshots to the listing in the F-Droid Store.
Descriptions/ images can either be added to this repo or to https://gitlab.com/fdroid/fdroiddata/tree/master/metadata

Tusky in the F-Droid Store: https://f-droid.org/en/packages/com.keylesspalace.tusky/

How to add screens to F-Droid: https://f-droid.org/en/docs/All_About_Descriptions_Graphics_and_Screenshots/

Fastlane's doc: https://docs.fastlane.tools/actions/supply/#images-and-screenshots

### CODE REVIEW

**Comment by connyduck** [comment]
Wow, thats super cool, thank you <3
Does this now override the descriptions from the fdroid metadata file?

I think it would make sense do delete the files from the `/assets` directory now, so we don't have to maintain them in two places, can you do that please?

**Comment by jaller94** [comment]
The F-Droid metadata file overrides this respository's metadata. But it
could be stored here to allow for tranlation, a file history and a more
detailed structure (not everthing in one file).

Essentially it's your call where you wish to keep the data. The Fastlane
folder has the benefit that it might be usable for automated deploys and
Pull requests by others (if there are errors, typos or new translations).

Yes, I can move the files from /assets/ to the new place. I am going to do
that tomorrow; it's late here.

https://gitlab.com/fdroid/fdroiddata/blob/master/metadata/com.keylesspalace.tusky.txt

**Comment by charlag** [comment]
Wow, that's super cool, thx!

**Comment by jaller94** [comment]
Used `git rebase` to have it see the rename instead of copying of images.

xedulrg2qsnzigytomfh_xfqlb

**Comment by jaller94** [comment]
Also added the feature list from the README to the full description. Felt like it was missing.

**Comment by Korb** [comment]
> add screenshots to the listing in the F-Droid Store.

Screenshots are currently displayed on [the web version](https://f-droid.org/packages/com.keylesspalace.tusky/) of the app catalog but are not displayed on the mobile client:

Screenshot_20221127_105158

**Comment by charlag** [comment]
I went to check and it indeed stopped showing up??

**Comment by connyduck** [comment]
Looks fine for me? Temporary F-Droid problem maybe?

**Comment by Korb** [comment]
(Sorry that the interface is in Russian - there is no way to change the language in the F-Droid mobile application.)

Screenshot_20221128_101823
Screenshot_2022_1128_101905
Screenshot_2022_1128_101924

1. Tusky (Tusky) — https://f-droid.org/packages/com.keylesspalace.tusky/
2. Tusky (Unknown application) — https://f-droid.org/packages/com.keylesspalace.tusky.test/

Screenshot_2022_1128_102540

**Pull request merged**
