### PR TITLE
improve usability: add shortcuts for compose/send new toot [#505]

### PR DESCRIPTION
**Pull request by unstabler**
https://twingyeo.kr/@cheesekun/102184993516052526

sorry for my bad english > <);

### CODE REVIEW

**Comment by connyduck** [comment]
In `MainActivity`, there is already code that handles key events. Can we merge the existing code with you new code somehow?

**Comment by unstabler** [comment]
um.. i think `onKeyDown` will be called for each key event. (ctrl + enter raises `onKeyDown(ctrl)` `onKeyDown(enter)` twice)

**Comment by connyduck** [comment]
yes, I understand that, but can you move the code from `onKeyDown` to `onKeyShortcut` and see if it still works?

**Comment by unstabler** [comment]
omg it works! :0

**Comment by connyduck** [comment]
Ok, I meant the other way round, but this is also fine. Thank you!

**Pull request merged**
