### PR TITLE
added emojicompat to views and used proper plumbing

### PR DESCRIPTION
**Pull request by sturmen**
so by default this will add missing emoji for all users (especially ones on older versions of Android that lack emoji like 🦖 or 🌯), while optionally allowing the user to replace her existing platform's emoji with the Google "Noto" emoji in all views.

🤯

### CODE REVIEW

**Comment by sturmen** [comment]
just realized that there was already an open PR with a lot of the same work. Is there a reason that #364 wasn't merged? How can I address any concerns in mine?

**Comment by charlag** [comment]
Cool, thanks, welcome to Tusky development 🐘
I cannot rememeber exactly but I think that @connyduck tried something with Twemoji and that PR was outdated?

**Comment by charlag** [comment]
You don't use bundled fonts if I understand correctly. I would like it to work without Play Services, honestly (and I think a lot if other people too)

**Comment by connyduck** [comment]
It MUST work without Playservices. I agree with @charlag, we don't want any dependencies on non free-services in Tusky.
Regarding the emojis... The ideal solution would be to have a setting where user can change between Twemoji and Android emojis, second best Twemoji only.

**Comment by sturmen** [comment]
Correct. I believe this is decoupled from Play Services since the Google Font provider is its own separate service, but I'll test it on a Play Services-less LineageOS install this evening.

I understand the desire for Twemoji support and I would like to see it as well. My reading of the current landscape is that with Oreo, Google has introduced a framework for different companies/organizations to host fonts for runtime download. At this point in time, Google Fonts is the only such provider but hopefully others will follow & a future provider will host Twemoji/EmojiOne.

In its current form, I think this is a tangible improvement for existing users while avoiding any noticeable technical debt. As we know, pre-8.0 emoji were tied to OS updates. That means that we have plenty of users lacking hundreds of emoji they may encounter. By integrating EmojiCompat in this PR, we fill all of those gaps for users (4.4+). I've included an optional toggle to replace *all* emoji with Noto, but it is disabled by default and the app's "emoji look" is unchanged from today.

In the future, having this in place will (as best I can surmise) make it easy to add other emoji sets once someone hosts them properly.

Will report back with behavior without Play Services.

**Comment by charlag** [comment]
I have very big dislike for Google but I could swallow it to bring emojis to users quick.
What I worry about is that we may get "anti-feature" badge on F-Droid? Or not?
I would bundle the font anyway (it is possible with custom FontRequest and it is in the docs)
Thanks once again for working on this and listening for our complains 😅

**Comment by sturmen** [comment]
No worries! Like everyone else, I'm conflicted between the quality-of-life conveniences Google can provide vs. the justified desire to adhere to Free Software principles.

**Comment by sturmen** [comment]
Without Google Play Services, it fails. This failure is silent to the user and the app continues to otherwise work as it always has. I don't know F-Droid's policy on flagging it as an anti-feature, but if so then I think this PR is worth declining.
```
02-09 09:32:48.203  7952  7952 E TuskyApplication: EmojiCompat initialization failed
02-09 09:32:48.203  7952  7952 E TuskyApplication: java.lang.RuntimeException: provider not found
02-09 09:32:48.203  7952  7952 E TuskyApplication: 	at android.support.text.emoji.FontRequestEmojiCompatConfig$FontRequestMetadataLoader.retrieveFontInfo(FontRequestEmojiCompatConfig.java:229)
02-09 09:32:48.203  7952  7952 E TuskyApplication: 	at android.support.text.emoji.FontRequestEmojiCompatConfig$FontRequestMetadataLoader.createMetadata(FontRequestEmojiCompatConfig.java:290)
02-09 09:32:48.203  7952  7952 E TuskyApplication: 	at android.support.text.emoji.FontRequestEmojiCompatConfig$FontRequestMetadataLoader.access$100(FontRequestEmojiCompatConfig.java:164)
02-09 09:32:48.203  7952  7952 E TuskyApplication: 	at android.support.text.emoji.FontRequestEmojiCompatConfig$FontRequestMetadataLoader$1.run(FontRequestEmojiCompatConfig.java:218)
02-09 09:32:48.203  7952  7952 E TuskyApplication: 	at android.os.Handler.handleCallback(Handler.java:751)
02-09 09:32:48.203  7952  7952 E TuskyApplication: 	at android.os.Handler.dispatchMessage(Handler.java:95)
02-09 09:32:48.203  7952  7952 E TuskyApplication: 	at android.os.Looper.loop(Looper.java:154)
02-09 09:32:48.203  7952  7952 E TuskyApplication: 	at android.os.HandlerThread.run(HandlerThread.java:61)
02-09 09:32:48.203  7952  7952 E TuskyApplication: Caused by: android.content.pm.PackageManager$NameNotFoundException: No package found for authority: com.google.android.gms.fonts
02-09 09:32:48.203  7952  7952 E TuskyApplication: 	at android.support.v4.provider.FontsContractCompat.getProvider(FontsContractCompat.java:735)
02-09 09:32:48.203  7952  7952 E TuskyApplication: 	at android.support.v4.provider.FontsContractCompat.fetchFonts(FontsContractCompat.java:715)
02-09 09:32:48.203  7952  7952 E TuskyApplication: 	at android.support.text.emoji.FontRequestEmojiCompatConfig$FontProviderHelper.fetchFonts(FontRequestEmojiCompatConfig.java:334)
02-09 09:32:48.203  7952  7952 E TuskyApplication: 	at android.support.text.emoji.FontRequestEmojiCompatConfig$FontRequestMetadataLoader.retrieveFontInfo(FontRequestEmojiCompatConfig.java:227)
02-09 09:32:48.203  7952  7952 E TuskyApplication: 	... 7 more
```

**Comment by charlag** [comment]
You could try to use embedded font?
https://developer.android.com/guide/topics/ui/look-and-feel/emoji-compat.html#bundled-fonts

**Comment by sturmen** [comment]
I'm happy to do the work of an embedded font, I'm just wary of blowing up the APK size like that. I feel that's a "product decision", if you will. I'll bundle in the fonts and see what sort of output size we get.

**Comment by charlag** [comment]
@sturmen cool! Thanks. I don't think that APK will be super huge because of that.

**Comment by connyduck** [comment]
I just made a production build with this PR+bundled font. The apk size is at 9mb, compared to the 2.4mb we have now. `NotoColorEmojiCompat.ttf` has over 7mb.

I also tried to make my own bundled EmojiCompat.Config with twemoji fonts from https://github.com/eosrei/twemoji-color-font and https://github.com/ingrinder/twemoji-android to no avail. 

What works really well is this library https://github.com/vanniktech/Emoji/, it one adds about 3mb to apk size because it uses smaller bitmaps. Unfortunately I did not get it to work with `AppCompatMultiAutoCompleteTextView` and we definitely need that (but this can be solved, may require a fork of the library though). Also it is not (yet) on the newest twemoji version.

My concerns with this Pullrequest are: 
- if we merge it, we may have no chance to add Twemojis later on
- we need to add a lot of apk size to get it to work for fdroid users, but we only solve the problem of adding newer emojis for older devices, which I do not consider to be a big problem for our users. And we are in the progress of stopping support for older Androids anyway.
- one feature we need, is an emoji keyboard for the Mastodon custom emojis, and it would be nice to have non-custom emojis in there as well. But a switch in the settings to use platform/compat makes implementing an emoji keyboard quite a bit more complex.

**Comment by remi6397** [comment]
What about downloading that font from self-hosted service (rawgit maybe?) in runtime on user's request (or when legacy Android is detected)? It's probably possible to do, but is it worth work?

**Comment by charlag** [comment]
What to consider legacy? We want Twemoji for everyone, also

**Comment by remi6397** [comment]
@charlag, legacy android means that it's older than the latest version officially distributed by Google on their latest reference phones. In this situation legacy android lacks latest emoji. ;-)

**Comment by sturmen** [comment]
Sorry I dropped the ball on doing size comparisons myself. Thanks @connyduck for doing them. It seems like the best path going forward is skipping Google's solution and forking vanniktech/emoji to fit the needs of Tusky. Perhaps @vanniktech will allow the changes to make it upstream?

**Comment by vanniktech** [comment]
Hmmm?

**Comment by charlag** [comment]
@vanniktech There's a problem with `AutomCompleteTextView' and your Emoji library, we consider making some changes. Would you accept them upstream?

**Comment by connyduck** [comment]
@vanniktech yes we would need a AutoCompleteTextView with emoji support. But making the required methods public in your library would help us as well. I can make a pull request so you can have a look.

**Comment by vanniktech** [comment]
Sure create a PR.

**Comment by connyduck** [comment]
No need to create a PR, the changes we want are already in https://github.com/vanniktech/Emoji/commit/3f6518865fe21d688cf5c76c89a6abbd61c46c21. A new release would be nice though! @vanniktech @charlag

**Comment by vanniktech** [comment]
There's a problem currently with EmojiOne and I'm waiting for them to fix it before making a release. https://github.com/vanniktech/Emoji/issues/259

**Pull request closed without merging**
