### PR TITLE
Add image descriptions indicator. Closes #683

### LINKED ISSUE #683: Make it easier to remember adding image descriptions for visually impaired people
I have published countless images without a description for visually impaired people. I guess it would be easier to remember if a few modifications were done:
- right after the upload, Tusky would focus on a text field for description
- next to this text field there is an icon such as :question: or :information_source: that explains why this is important
- the user has to write a text and press Add or press Cancel

* * * *
- Tusky Version: 1.8.0 (downloaded from F-Droid)
- Android Version: 7.1.2 (LineageOS 14.1)
- Android Device: Moto G (falcon)
- Mastodon instance (if applicable): https://masto.donte.com.br

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

### PR DESCRIPTION
**Pull request by charlag**
This PR adds small check mark in the corner of the image preview in ComposeActivity.
It works. the only problem is visibility of the check mark. We either need different colors for it or some kind of a circle underneath it.

### CODE REVIEW

**Comment by charlag** [comment]
Examples here
https://birb.site/@charlag/100289848956672798

**Comment by connyduck** [comment]
I think it should look somewhat like this (quick mockup with GIMP)

**Comment by connyduck** [comment]
(unrelated: Do you have any idea why the thumbnail is so pixelized?)

**Comment by charlag** [comment]
Looks fine to me. And what do you think should be unselected state?

**Comment by charlag** [comment]
I can check with regular ImageViews, I hope that's pixelated not because I'm doing some dark magic with canvas.
Other theories:
- we scale them down this way
- we don't scale them down enough so the system fits them there somehow and it looks bad

**Comment by connyduck** [comment]
Grey background with a exclamation mark for unselected state? I think I would have to try it out how it feels in action to be sure

> I can check with regular ImageViews, I hope that's pixelated not because I'm doing some dark magic with canvas.

Its super unimportant honestly, if it is not much effort we should fix it though

**Comment by charlag** [comment]
I've tried commenting out all the preview drawing code and image previews are still bad. So I think it is not my fault.

**Comment by connyduck** [comment]
Why the A? I have no idea what it could mean and would really prefer good icons.
Also I think it would look better if it was a real badge (=another view) that can overlap the ImageView instead of being drawn on the ImageView.

**Comment by charlag** [comment]
I was looking for a better symbol than generic checkmark.
I'm not sure why would it look better, could you elaborate? We can create separate views, of course, if it provides better UX

**Comment by connyduck** [comment]
What about this icon? https://materialdesignicons.com/icon/spellcheck

I think its better because you can see it is not part of the image in all cases.

**Comment by charlag** [comment]
I think this may work
-- 
Sincerely,
Ivan



10 Jul 2018, 21:36 by notifications@github.com:

**Comment by connyduck** [comment]
are you still working on this?

**Comment by charlag** [comment]
Yes, but I was quite busy. Should I finish this or start with avatars?

**Comment by connyduck** [comment]
As you want :)
I would like to have both in Tusky 3 https://github.com/tuskyapp/Tusky/milestone/9

**Comment by charlag** [comment]
Also, are you firm on your decision on making badge another view opposed to drawing on top? For me drawing is easier I guess because it requires less refactoring

**Comment by connyduck** [comment]
Nope, draw on top. But please change the icons. :)

**Comment by charlag** [comment]
It looks nice but I'm not sure if it's clear/annoying enough

Maybe use [this](https://materialdesignicons.com/icon/format-annotation-plus) icon when it's not added? Maybe it's enough and I'm overthinking

screenshot_tusky_20180728-185401
screenshot_tusky_20180728-185353

**Comment by connyduck** [comment]
I think its good enough to release it to nightly/beta, lets see what users think & then maybe change it?

**Comment by charlag** [comment]
Yea, of course!

**Pull request merged**
