### PR TITLE
Disable click on preference category items

### PR DESCRIPTION
**Pull request by pandasoft0**
Disable click on preference category items. tuskyapp#1221

- Create a new class derived from the PreferenceCategory class, override binding and disable click listener ( i didn't find a better way because it set the click listener on binding without any chance to disable it)
- Change PreferenceScreen to androidx PreferenceScreen, changed SwitchPreference to SwitchPreferenceCompat according to [Settings Guide](https://developer.android.com/guide/topics/ui/settings.html)

### CODE REVIEW

**Comment by pandasoft0** [comment]
Sorry, I didn't find this simple solution... Updated code.

**Comment by connyduck** [comment]
LOL this was actually a bug in the library, see the changelog https://developer.android.com/jetpack/androidx/releases/preference

**Comment by pandasoft0** [comment]
I will check it with updated library

**Comment by pandasoft0** [comment]
Yes, "shouldDisableView" can be safety removed. I will create a new PR is few minutes.

**Pull request merged**
