### PR TITLE
Address overlap of name/time in status display

### PR DESCRIPTION
**Pull request by gtcompscientist**
Use a ConstraintLayout and LinearLayout to better manage the size of the names.

### CODE REVIEW

**Comment by gtcompscientist** [comment]
Fair enough. I've dug in and I think I have a way to lay out the entire thing as a flat ConstraintLayout, I'll let you know when that is done.

**Comment by gtcompscientist** [comment]
@connyduck So, I was able to get the layout entirely flat, or nearly flat. The two ways break down like this:

1. Entirely flat requires setting the display name/username as a `SpannedString` (to bold the display name)
1. Nearly flat flattens the entire rest of the layout but leaves the `LinearLayout` to manage the ellipsizing.

Happy to go with whichever you prefer.

**Comment by connyduck** [comment]
Awesome. I think I prefer the option with the `LinearLayout` as we end up with less code in the adapter?
But please do as you want, I will merge both!

**Comment by charlag** [comment]
@gtcompscientist do you plan working on this further? (no rush, just going through everything I've missed)

**Comment by connyduck** [comment]
-> #967

**Pull request closed without merging**
