### PR TITLE
fix notification message formatting when username is not at the beginning of the message

### PR DESCRIPTION
**Pull request by connyduck**
closes https://github.com/tuskyapp/Tusky/issues/2521

### CODE REVIEW

**Review by Tak — APPROVED** [review]
I guess it could still go wrong if the text preceding the display name happens to also contain the display name, but that seems extremely unlikely

**Review by charlag — APPROVED** [review]
I'm not sure if it would be more reliable to look for the placeholder position in the template? Probably not.

**Comment by connyduck** [comment]
> I'm not sure if it would be more reliable to look for the placeholder position in the template? Probably not.

Good idea. It's better because it does not rely on user controlled input.

**Review by charlag — APPROVED** [review]
Seems okay, I hope it works with RTL too, RTL should be about just display, not order of characters

**Comment by connyduck** [comment]
yes it does, I tried it out

**Pull request merged**
