### PR TITLE
Work around "Illegal reflective access" warnings in kapt

### PR DESCRIPTION
**Pull request by nikclayton**
See https://youtrack.jetbrains.com/issue/KT-30589/Kapt-An-illegal-reflective-access-operation-has-occurred for details.

### CODE REVIEW

**Comment by nikclayton** [comment]
The warning breaks incremental compilation, so fixing this significantly improves the developer experience.

**Comment by charlag** [comment]
the linked SO answer says it's not needed with JDK 16 anymore though?

**Comment by nikclayton** [comment]
> the linked SO answer says it's not needed with JDK 16 anymore though?

We currently use 11.

**Comment by nikclayton** [comment]
Now on Java 17, so this is not necessary.

**Pull request closed without merging**
