### PR TITLE
Implement reply count indicator to track web UI

### PR DESCRIPTION
**Pull request by Tak**
Addresses #882 

Web UI:
web-detailed web-timeline

Tusky:
tusky-detailed tusky-timeline

### CODE REVIEW

**Comment by connyduck** [comment]
Tbh I don't like this. It pollutes the the otherwise clean interface and I don't think the information is worth it. 

What about showing the number only on detail statuses? I'd be fine with that.

(also, BottomSheetActivityTest.kt is failing)

**Comment by charlag** [comment]
I've grown to accept it in web. I don't think it makes too much sense to show it in detail because this indicator serves exactly the purpose of showing if status if worth opening.

Maybe we could find anything super subtle or make it optional? Don't want to deviate from web too much.
Also I don't think it's needed inside thread?

**Comment by Tak** [comment]
Oh, I thought we would want to keep parity with the web ui (which also has them in threads).

I find them nice for knowing whether there's a point to expanding the thread (even more in Tusky, where it doesn't just populate a column, but replaces the full screen view), but I don't feel _super_ strongly about it.

**Comment by charlag** [comment]
Oh, I've never noticed them in threads, actually. My bad.

-- 
Sincerely,
Ivan



13 Oct 2018, 07:52 by notifications@github.com:

**Comment by charlag** [comment]
@connyduck are you still against this? I don't notice them in web anymore but I don't find them terribly useful either

**Comment by connyduck** [comment]
> @connyduck are you still against this? 

yes (sorry @Tak). At least for main timelines. We could add it for detailed statuses, but doesn't make too much sense since one can already see all replies there.

**Pull request closed without merging**
