### PR TITLE
Bump compileSdk to 34

### PR DESCRIPTION
**Pull request by Goooler**

### CODE REVIEW

**Comment by connyduck** [comment]
Should we also have a look how the predictive back gesture works with Tusky?

Related issue: #4005

**Comment by Goooler** [comment]
This is just bumping `compileSdk`, which is irrelevant to `targetSdk`?

**Comment by connyduck** [comment]
I see. I usually do them together but I guess this works as well.

**Comment by connyduck** [comment]
There are some new deprecations which should probably be addressed:
`overrideActivityTransition`
`startActivityAndCollapse` - this one apparently throws `UnsupportedOperationException` on Upside Down Cake

**Pull request closed without merging**
