### PR TITLE
Better screen transitions

### PR DESCRIPTION
**Pull request by charlag**
I mostly took Android 13 transitions and removed the sliding for the "deeper"/background one because "extend" animations are not available until Android 13.

Here are the original ones: https://cs.android.com/android/platform/superproject/+/android-13.0.0_r8:frameworks/base/core/res/res/anim/;bpv=1

Initially I've made separate versions fro Android 13+ that are close to the original but I think it's not worth it to keep both.

https://github.com/tuskyapp/Tusky/assets/3099142/616fc40c-f944-45b4-bf6f-167f62d30493

### CODE REVIEW

**Comment by charlag** [comment]
Noticed that "home timeline" preferences transition are slightly broken because fragment has no background color

**Review by connyduck — APPROVED** [review]
very nice

**Comment by charlag** [comment]
should I merge it?

**Comment by connyduck** [comment]
I was just waiting for Google Play to publish a nightly, because every new upload resets the position in the queue and most of the recent changes haven't been published. They have now.

**Pull request merged**
