### PR TITLE
Prevent multiple regist to eventHub on same TimelineFlagment

### PR DESCRIPTION
**Pull request by kyori19**
https://github.com/tuskyapp/Tusky/blob/6cad8feea2f7c1abcb68ff0944c2571fa50c8627/app/src/main/java/com/keylesspalace/tusky/fragment/TimelineFragment.java#L381-L384

onActivityCreated is called every time when switching tabs.
Since subscribe is called every time when switching tab, it gets timeline unnecessarily many times after toot.

### CODE REVIEW

**Comment by connyduck** [comment]
Indeed it does, nice find. I just wonder if there isnt a better solution to this, like moving the subscribtion to `onCreate`?

**Comment by charlag** [comment]
Hi!
Thanks for the help, we could really miss that (these fragment lifecycles, oh.
I would prefer to move it to something which is executed only once but that's probably nowhere to be found, I think.

I'll try it out later this week

**Comment by charlag** [comment]
@connyduck it is risky because we may need UI, we should check that manually

**Comment by kyori19** [comment]
Thanks for your reply.
@connyduck I already tried to move to onCreate but app crashed because we need UI.

**Comment by Tak** [comment]
Aha, I bet this addresses #880

**Pull request merged**
