### PR TITLE
Russian language updated

### PR DESCRIPTION
**Pull request by MasterGroosha**
New strings:
• Undo actions for boost/favourite.
• New theme (as is system).
• Renamed «Tabs» to «Filters» in Settings to avoid option name duplicate.
• Added new lines for Filters feature.

### CODE REVIEW

**Comment by charlag** [comment]
Hey
Why you didn't submit it through Crowdin?

**Comment by MasterGroosha** [comment]
IIRC, Crowdin has some problems with Russian language (handling "few" or so on), encountered this with Mastodon, so I had to manually update langs there.
Aaaaaand I'm doing the same for Tusky.

**Comment by charlag** [comment]
Oh, that doesn't sound good.
You didn't update any plurals tho?..

**Comment by MasterGroosha** [comment]
Not in this commit. @connyduck has disabled Russian language sync with Crowdin recently, btw.

If it really matters, I can start using Crowdin. However, since I'm used to build Tusky myself to test language updates, manual editing is preferred (for me only).

**Comment by charlag** [comment]
I have no problems with that, just curious.

**Pull request merged**
