### PR TITLE
Add a badge on account to show the date the user has joined mastodon

### PR DESCRIPTION
**Pull request by ademar111190**
The account creation date looks pretty useful to be shown to the user, it can bring valuable information especially to identify recently created accounts.

It is possible to get that information through the `created_at` field as mentioned [on this issue](https://github.com/tuskyapp/Tusky/issues/1487)

This MR unlocks the possibility to solve that issue, I did not solve that issue yet because that functionality looks a little bit advanced, so I think it should be enabled through settings option, so it is better to wait for the [settings refactor](https://github.com/tuskyapp/Tusky/pull/1615) to finish before implementing it.

Twitter for instance shows the joined date, probably to help to identify fake accounts, not sure:

twitter_example

Here some screenshots of how the app looks like with the changes:

|Before|After|
|---|---|
|before_1|after_1|
|before_2|after_2|
|before_3|after_3|

### CODE REVIEW

**Comment by connyduck** [comment]
I am not sure if we want this. On one hand it might help to identify spambots, on the other it might make it harder for newer accounts to be taken seriously.

**Comment by charlag** [comment]
I would be opposed to it because it's easy to fake but all other numbers are easy to fake too...

**Comment by charlag** [comment]
And it doesn't need a preference because there's no actual behavior change

**Comment by ademar111190** [comment]
I understood the points, I do not disagree, the last thing I want is to make it harder for newcomers to fully enjoy the platform, moreover, I could create my own instance and put any date I want…

In another hand, I would love to have that piece of information, generally, that information is precise.

So would you consider the possibility of this functionality be turned off by default, but possible to enable through the settings?

I can make that change if you guys agree…

**Comment by charlag** [comment]
I think we either should include it or not, pref does not make sense.
People on fedi pointed our that it's shown in web interface (and on static pages of masto too) so I would say "yes".
I think we should discuss design separately, I wouldn't put it in bubble e.g. but let's first hear more people.

**Comment by a1batross** [comment]
That would make sense in some kind of "moderation mode" but it's useless for normal users IMHO.

**Comment by connyduck** [comment]
There is no value in this information, and if you still need it you can get it with two clicks.

**Pull request closed without merging**
