### PR TITLE
Updated sv (Swedish) translation

### PR DESCRIPTION
**Pull request by iah**
Commit made via [Stringlate](https://lonamiwebs.github.io/stringlate/)

### CODE REVIEW

**Comment by connyduck** [comment]
Looks like you started this from the wrong branch :/

**Comment by iah** [comment]
Isn't this master?

**Comment by connyduck** [comment]
Yes master is the default branch, but your pull request contains commits from another branch. I think you have to do "Update strings.xml" -> "Pull new strings" -> "master" in Stringlate and try again.

**Comment by iah** [comment]
I made a new pr. Please check it.

**Comment by connyduck** [comment]
no, its the same problem :/

**Pull request closed without merging**
