### PR TITLE
Don't interpret html inside poll options.

### LINKED ISSUE #1362: Tusky shows html rich text in poll options
Mastodon WebUI [https://odakyu.app/@ars42525/102376895437413871](https://odakyu.app/@ars42525/102376895437413871) 
Screenshot_20190703-185117

Tusky
Screenshot_20190703-185106

HTML tags should be escaped before showing it

* * * *
- Tusky Version: 8.0 dc76a82f 
- Android Version: 8.0.0
- Android Device: G8441
- Mastodon instance (if applicable): odakyu.app

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

### PR DESCRIPTION
**Pull request by Tak**
Fixes #1362

### CODE REVIEW

**Comment by Tak** [comment]
Sorry, I thought that renaming the resource would have that effect?

**Comment by connyduck** [comment]
Its just to get rid of the unused old string that is in all translations

**Comment by Tak** [comment]
Updated - I wonder, should it maybe just be marked untranslatable? (It's the same now in all existing translations, I'm just not sure whether there would ever be a translation that would do it differently)

**Comment by connyduck** [comment]
Im not sure, maybe it is different in some language? But yes for now its probably better to move it in donottranslate.xml

**Comment by Tak** [comment]
Ok, moved

**Pull request merged**
