### PR TITLE
Update CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by bonsaiheldin**

### CODE REVIEW

**Comment by connyduck** [comment]
haha, nice.
Actually, the API level 21 mention is also outdated, because we stopped supporting anything lower. Can you delete that sentence as well?

**Comment by bonsaiheldin** [comment]
Done.

**Comment by connyduck** [comment]
Awesome, thx!

**Comment by bonsaiheldin** [comment]
Actually my phrasing is a bit wrong. I wrote that anything below 21 is not supported anymore, indicating that 21 still is.

Oh well. :woman_shrugging:

**Pull request merged**
