### PR TITLE
Minimizes keyboard on search screen

### PR DESCRIPTION
**Pull request by andrewhamilton0**
Adds feature if user clicks on toolbar, on the pages box, or on the tabs buttons that the keyboard will minimize and focus will be taken off of search bar.

Further addresses issue #4573

### CODE REVIEW

**Comment by connyduck** [comment]
I'm not sure this is necessary

**Comment by andrewhamilton0** [comment]
> I'm not sure this is necessary

I noticed that after I performed a search, the text box becomes unfocused as expected. But then I went to edit the search, clicked the text box,  and then I decided not to edit it. The only way to get rid of the focus was to perform the search, even if I clicked into pager items and back. 

I was confused why it was doing this at first as I thought I fixed the bug but I had forgot I re-clicked on the text box without editing and completing a search.

It's not the biggest deal, but I do find it as a nice feature, but I do understand if you find it unnecessary.

**Comment by connyduck** [comment]
Ok, I tried it out and I guess it makes sense. But the keyboard should alse be hidden when switching tabs, no?

**Comment by andrewhamilton0** [comment]
> Ok, I tried it out and I guess it makes sense. But the keyboard should alse be hidden when switching tabs, no?

Yes you're right! I went ahead and added that functionality as well!

**Review by connyduck — APPROVED** [review]

**Pull request merged**
