### PR TITLE
fix buttons and usernames overlapping in follow requests

### PR DESCRIPTION
**Pull request by connyduck**
Before / After

### CODE REVIEW

**Comment by Lakoja** [comment]
Observation: names on the left can all be read fully on the right only two.

**Comment by connyduck** [comment]
True. One can click through to the full profile if it is a problem.

**Comment by Lakoja** [comment]
As an idea (or maybe future further step): Shouldn't there be more info directly in this list to facilitate direct decisions.
If so the single entries would be much bigger and have room for a full ine address.

(However I'm not sure which additional information...)

**Review by charlag — APPROVED** [review]

**Comment by connyduck** [comment]
The idea is not bad, consider openening an issue @Lakoja

**Pull request merged**
