### PR TITLE
Enable boosting of own private toots, closes #664

### LINKED ISSUE #664: Enable boosting of own private toots

### PR DESCRIPTION
**Pull request by Pangoraw**
The implementation is the same as on the web version. Meaning that the visibility icons stays the same unless the toot has been boosted (in this case an "active" version of the lock is shown) and you boost and unboost from the popup menu.

I had to add `onReblog` as an abstract method on `SFragment` in order to be able to boost from the popup menu. I don't know if this is a problem.

I also renamed `reblog_disabled_*` into `reblog_private_*` since reblog isn't disabled anymore in this case.

### CODE REVIEW

**Comment by connyduck** [comment]
it crashes for me when opening the more menu of a status
 ```java.lang.NullPointerException: Attempt to invoke virtual method 'boolean
com.keylesspalace.tusky.entity.Status.getReblogged()' on a null object reference
        at com.keylesspalace.tusky.fragment.SFragment.more(SFragment.java:157)
        at com.keylesspalace.tusky.fragment.TimelineFragment.onMore(TimelineFragment.java:520)
        at com.keylesspalace.tusky.adapter.StatusBaseViewHolder$5.onClick(StatusBaseViewHolder.java:456)
        at android.view.View.performClick(View.java:4761)
        at android.view.View$PerformClick.run(View.java:19767)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:135)
        at android.app.ActivityThread.main(ActivityThread.java:5310)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:901)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:696)
```

**Comment by Pangoraw** [comment]
Fixed it, and squashed it. It should be all set now ! :+1:

**Comment by charlag** [comment]
I'll try to take a look closer to the weekend, sorry, a really busy week. Thanks for the PR!

**Comment by charlag** [comment]
Actually it's pretty small so if @connyduck says it's okay I'm okay with it too, just let it build ;)
Congrats on the merged PR :confetti_ball:

**Pull request merged**
