### PR TITLE
fix black theme on Android 12

### PR DESCRIPTION
**Pull request by connyduck**
This new splashscreen is causing so much trouble 😠 

before & after

### CODE REVIEW

**Review by charlag — APPROVED** [review]
I don't know what the bug was but okay

**Comment by charlag** [comment]
I mean I *see* it but I don't know *why*

**Comment by connyduck** [comment]
Wait the splash screen does still not work as intended. It shows on some devices after Login. Putting it on LoginActivity instead of MainActivity would show it when adding an account. 🙄 
SplashActivity has to come back.

**Comment by charlag** [comment]
Multiple activities was a mistake

**Comment by connyduck** [comment]
> Multiple activities was a mistake

Yes. Another thing we should refactor D:

**Review by charlag — APPROVED** [review]

**Pull request merged**
