### PR TITLE
[OC] first version of the translation

### PR DESCRIPTION
**Pull request by Quenty31**
I'll make more changes soon, so it matches the same wording as in the Mastodon UI.

### CODE REVIEW

**Comment by charlag** [comment]
Cool, thanks!

**Comment by BoFFire** [comment]
Nice :) Thank you @Quenty31 ! \o/

**Comment by connyduck** [comment]
Is this ready to merge? @Quenty31

**Comment by Quenty31** [comment]
Yes it is! I made some commits, now it's okay :)

**Comment by connyduck** [comment]
Thank you so much <3

**Pull request merged**
