### PR TITLE
Improve protection against accidentally losing drafts and redrafts

### PR DESCRIPTION
**Pull request by Tak**

### CODE REVIEW

**Comment by connyduck** [comment]
I don't think this is the right fix for the problem. You end up with a saved toot even when you decide to send the status.
Can you try initializing the ViewModel differently so the `didChange` check always returns true when its a redraft? But not when its editing a draft.

**Comment by Tak** [comment]
Hm, we delete drafts on sending in any case.
But I can rework it.

**Comment by connyduck** [comment]
We only delete drafts when we have their id

**Comment by Tak** [comment]
Reworked

**Comment by connyduck** [comment]
But we already have `startingText` and `startingContentWarning` in the ViewModel, having it in the Activity as well is super confusing

**Comment by Tak** [comment]
Hm, this iteration has broken mentions in replies and reply context when editing drafts 😐

**Comment by Tak** [comment]
I finally got around to rereworking this.
Now the view model just sets a flag when we want to mark the initial state as modified.

We're doing this in the case of redraft, but also in the case of editing a saved draft now, because saved drafts are now deleted when you start editing them.

**Review by connyduck — APPROVED** [review]

**Comment by digitalcircuit** [comment]
Thank you for your efforts here!

In the past, I've lost several lengthy toots due to temporarily pausing Digital Wellbeing's Focus Mode, redrafting a toot, only for Focus Mode to close Tusky when the break was over before I finished editing, thus discarding the previously deleted-for-redrafting toot.

**Comment by Tak** [comment]
🤔 Does this change actually help in that case?

**Comment by digitalcircuit** [comment]
@Tak Ack, sorry for the noise, in my enthusiasm upon checking the `develop` commit history, I misread the progression of changes here and the commit message.  This probably doesn't actually help the 'app is effectively swiped away' behavior of Focus Mode activating.

**Comment by Tak** [comment]
There's a request for autosave ( #1540 ) - that would probably mitigate the issue somewhat

**Pull request merged**
