### PR TITLE
tuskyapp/Tusky#1028 Fix issue with share file Uri

### PR DESCRIPTION
**Pull request by pandasoft0**
Add file Uri support.
May fix the tuskyapp/Tusky#995 also

### CODE REVIEW

**Comment by charlag** [comment]
Hey
Thanks for the PR, I only had a brief look but I'll try to check it this weekend

**Comment by connyduck** [comment]
Whats the issue with file uris? Why do we need it?

**Comment by connyduck** [comment]
Ah did not see the #1028, sorry. Will review tomorrow.

**Comment by pandasoft0** [comment]
@connyduck Updated to use FileProvider

**Comment by connyduck** [comment]
Can you tell me how to reproduce the issue this PR fixes?

**Pull request closed without merging**
