### PR TITLE
Upgrade AndroidX dependencies

### PR DESCRIPTION
**Pull request by connyduck**
and use new `@Upsert` from Room

### CODE REVIEW

**Comment by connyduck** [comment]
Uh oh this crashes the app on every placeholder in timelines. But nice that it was caught by tests.

**Comment by nikclayton** [comment]
I haven't checked yet, but it would be worth seeing if the recyclerview update fixes the problem with horizontal swipe sensitivity being too high without needing my hack. The release notes mention better nested scrolling support (and ViewPager2 wraps a RecyclerView around a RecyclerView, which is what causes the problem).

**Comment by connyduck** [comment]
Yes, I also didn't notice a difference

**Review by charlag — APPROVED** [review]

**Comment by Goooler** [comment]
Can also add Kotlin 1.8.10 update here.

https://github.com/JetBrains/kotlin/releases/tag/v1.8.10

**Comment by Goooler** [comment]
And if we can enable @renovate-bot for this repo?

**Comment by connyduck** [comment]
> And if we can enable @renovate-bot for this repo?

We can try

**Pull request merged**
