### PR TITLE
Show target domains for non-mention/non-hashtag links where the target domain is not provided or differs from the domain in the text

### PR DESCRIPTION
**Pull request by Tak**
Addresses #2694

My *instinct* is to spend more time trying not to iterate the content multiple times, but maybe it's ok because many posts don't contain links/tags/mentions, and they only have a few when they do 🤷 

Screen Shot 2022-09-13 at 10 07 17

### CODE REVIEW

**Comment by connyduck** [comment]
Nice, but I am also seeing it in mentions both in profiles and in posts:
Screenshot_20220913_202746

**Comment by Tak** [comment]
🤔 I expect it in the profile, because we don't pass `mentions` there, but I don't understand why you're seeing it in the post below - in fact, I don't see it locally on exactly the same activity/post.

I could also back down on the mention/hashtag verification and just not display it for linked text that starts with `@`/`#`?

**Comment by Tak** [comment]
Screenshot_20220914-102053

**Comment by connyduck** [comment]
In the profile it is because there we have no `mentions` array, and in the post where you mention maloki it is because the url of the mention is https://rage.love/users/maloki but the one of the Span is https://rage.love/@maloki
You probably don't see it because we are on different instances.

> I could also back down on the mention/hashtag verification and just not display it for linked text that starts with @/#?

That is probably the solution, yes

**Comment by Tak** [comment]
> the url of the mention is https://rage.love/users/maloki but the one of the Span is https://rage.love/@maloki
h...uh

So if you tap that mention, it goes through the whole "looking up" thing, like when we see a normal url that looks like it could be a mention?

**Pull request merged**
