### PR TITLE
upgrade autodispose

### PR DESCRIPTION
**Pull request by connyduck**
They renamed the extension function from `autoDisposable` to `autoDispose`

### CODE REVIEW

**Comment by charlag** [comment]
Should we disable hiding to save on allocations? https://github.com/uber/AutoDispose/pull/376
I think we don't need to protect things from ourselves

Their new `withScope()` is :fire: 
Feels like some Ruby magic except there's no magic.

**Comment by connyduck** [comment]
So I should set `AutoDisposePlugins#setHideProxies()` to false somewhere in our Application class and it will improve performance?

**Comment by charlag** [comment]
That's how I understand it. The difference is probably marginal but it may add up with many streams

**Comment by connyduck** [comment]
nice, thx for the tip

**Pull request merged**
