### PR TITLE
Adjust list UX for platform consistency

### PR DESCRIPTION
**Pull request by nikclayton**
Most lists in the app use (explicitly or implicitly) platform metrics for dimensions, text size, colour, and so on, possibly via styles.

A few don't, inadvertently using the user's setting for status text size

Fix these, and simplify code where possible.

- Use android attributes for padding and height, for consistent UX.

- Remove explicit usage of app:tabTextAppearance, rely on the style.

- Remove ListSelectionAdapter and item_picker_list.xml, and adjust TabPreferenceActivity to use an ArrayAdapter with simple_list_item_1.xml

- Simplify item_followed_hashtag.xml, consistent with item_list.xml.

Fixes https://github.com/tuskyapp/Tusky/issues/3131

### CODE REVIEW

**Comment by nikclayton** [comment]
Here are some before/after screenshots:

**Comment by nikclayton** [comment]
# Following hashtags

- No dividers (not necessary for single line content)
- List item text size is not affected by status text size

**Comment by nikclayton** [comment]
# Viewing lists

- No dividers (not necessary for single line content)
- List item text size is not affected by status text size

**Comment by nikclayton** [comment]
# Picking a list to add as a tab

- List item text size is not affected by status text size (in the dialog, and the background)

**Comment by nikclayton** [comment]
# Adding a new tab

- List item text is not affected by status text size

**Comment by nikclayton** [comment]
# Searching hashtags

- No dividers (not necessary for single line content)
- List item text size is not affected by status text size
- Tab titles ("POSTS", etc) text size is not affected by status text size

**Comment by nikclayton** [comment]
The account page also benefits from the tab titles text size fix.

**Comment by connyduck** [comment]
I think it is actually a feature that more things are affected by the status text size, the setting is jus tbadly named. But I'd like to hear from someone who actually uses it. https://chaos.social/@ConnyDuck/109677568422013580

**Comment by nikclayton** [comment]
I've put the dividers back for list items with UI affordances at the start/end of the item.

As to what text should change, I think the way to conceptualise this is that Tusky has two types of text

1. Those that are part of the "body" role (https://m3.material.io/styles/typography/overview).
2. Those that are part of the UI chrome

Status text on a timeline should be based on the "body" role (https://m3.material.io/styles/typography/overview). If the user wants to modify that they can, through the Tusky preference.

Everything else -- text on menus, the title/app bar, in lists (whether generated by the app, or e.g., in the preferences fragments), `EditView` when searching, tab titles, etc, etc, is part of the UI chrome). That way the UI is consistent with the type sizes on every other app on the user's device.

If the user wants to change the scale of the UI chrome on their device then Android's global settings let them do that (and Tusky does honour it).

**Comment by connyduck** [comment]
Yes, I agree that is technically the correct way to do things. But there are definitely users with limited eyesight for which the system settings are still not enough and helping them is more important than being technically correct.

The font size preference affects some places without any system behind it, so yes we should clean that up. Either by making it affect everything or by splitting it into two, one for body one for interface.

**Comment by nikclayton** [comment]
https://github.com/tuskyapp/Tusky/pull/3248 addresses the "Users still need a way to adjust the text size in UI chrome" concern.

**Review by connyduck — COMMENTED** [review]
I still think dividers should be everywhere. E.g. in hashtag search, when the hashtags are very short dividers make it easier to click on the other side of the screen and still hitting the right one.

Also, some lists have a ripple effect when clicked, and some don't. Should we do something about that as well?

**Comment by nikclayton** [comment]
> I still think dividers should be everywhere. E.g. in hashtag search, when the hashtags are very short dividers make it easier to click on the other side of the screen and still hitting the right one.

"everywhere" would encompass places like:

- the preferences screen
- the navigation menu
- creating / editing a filter
- menus when adding a tab
- etc

I've put it back on the hashtag search results.

> Also, some lists have a ripple effect when clicked, and some don't. Should we do something about that as well?

E.g., the "Account preferences > Followed hashtags" doesn't ripple because you can't interact with the whole list item, just the "Unfollow" button at the end of the item.

I added it to item_list.xml, as that is selectable.

**Review by connyduck — APPROVED** [review]

**Pull request merged**
