### PR TITLE
Update FilemojiCompat to version 3.2.6

### PR DESCRIPTION
**Pull request by C1710**
- Update okhttp (it has a vulnerability in the version currently used)
- Has some new version numbers
- Includes Microsoft's recently open-sourced [Fluent Emoji](https://github.com/microsoft/fluentui-emoji) set, although the EmojiCompat-build is currently a bit broken/incomplete. I think it still makes sense to list it anyway, as the most used emojis should work correctly (I pushed it to the end of the list though ad added a small notice).

### CODE REVIEW

**Comment by C1710** [comment]
Obsoletes #2662

**Comment by C1710** [comment]
Depends on #2719 (Or at least a more recent `compileSdkVersion`), as Emoji2 is incompatible with Compile SDK 31.

**Comment by connyduck** [comment]
2719 is merged!

**Comment by C1710** [comment]
> 2719 is merged!

Nice :D

I'll merge/rebase later

**Review by thebino — APPROVED** [review]

**Pull request merged**
