### PR TITLE
always show follow requests in main menu

### PR DESCRIPTION
**Pull request by connyduck**
closes https://github.com/tuskyapp/Tusky/issues/1775

At first I tried to solve this inside the `FollowRequestsAdapter`, but it was a mess with a lot of duplicate code and edge cases, so I decided to use the new `MergeAdapter` api.

Note: Since this is not super urgent, I would wait until the RecyclerView lib is at least a release candidate. Also `ViewHolder.getAdapterPosition()` is now deprecated, should migrate before merging.

### CODE REVIEW

**Comment by connyduck** [comment]
This is now ready for testing @charlag

**Comment by charlag** [comment]
@connyduck will try to have a look today

**Comment by charlag** [comment]
Seems to work! I think header formatting looks a bit strange but it's okay.
Next step: showing the number in the side menu?

**Review by charlag — APPROVED** [review]

**Comment by connyduck** [comment]
Yes, that would be cool. I think we will need an additional network request for it though.

**Comment by charlag** [comment]
I think another request is worth it, maybe with some time limit

**Pull request merged**
