### PR TITLE
fix crash in NotificationsFragment

### PR DESCRIPTION
**Pull request by connyduck**
Steps to reproduce:
Have the default tab setup. Go to Account Settings -> Tabs. Go back. After a short time, crash.

<details>
<summary>Stacktrace</summary>

```
 java.lang.ArrayIndexOutOfBoundsException: length=33; index=-1
        at java.util.ArrayList.get(ArrayList.java:439)
        at com.keylesspalace.tusky.util.PairedList.get(PairedList.java:53)
        at com.keylesspalace.tusky.fragment.NotificationsFragment.addItems(NotificationsFragment.java:818)
        at com.keylesspalace.tusky.fragment.NotificationsFragment.onFetchNotificationsSuccess(NotificationsFragment.java:705)
        at com.keylesspalace.tusky.fragment.NotificationsFragment.access$400(NotificationsFragment.java:93)
        at com.keylesspalace.tusky.fragment.NotificationsFragment$4.onResponse(NotificationsFragment.java:665)
        at retrofit2.ExecutorCallAdapterFactory$ExecutorCallbackCall$1$1.run(ExecutorCallAdapterFactory.java:71)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6718)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

</details>

Regression from #985 

Seems like the notifications array gets cleared but the adapter content does not when the fragment gets recreated. Calling `updateAdapter()` syncs the two and it no longer crashes.

I also added a check to not dispatch the `MainTabsChangedEvent` when nothing changed.

### CODE REVIEW

**Comment by charlag** [comment]
I think I get this crash on nightly not when I switch to distant tab (so that notifications one is destroyed) and back to notifications, there's a spinner on top of notifications and then it crashes. Cannot get a trace rn. I suspect that your fix changing tabs content won't help?

**Comment by charlag** [comment]
Anyway, I will try to test it today or tomorrow morning to see if it helps. I'm not at home right now do it's a little bit harder.

**Comment by charlag** [comment]
Okay, i've checked it on my phone and it does fix the crash but I think we shouldn't reload notifications each time, that's not good for server load either. They're fetched in `onCreateView` which is obviously wrong. I'll check if I can solve this.

**Comment by charlag** [comment]
This works well I belive:


```java
Index: app/src/main/java/com/keylesspalace/tusky/fragment/NotificationsFragment.java
===================================================================
--- app/src/main/java/com/keylesspalace/tusky/fragment/NotificationsFragment.java	(revision c7ab0e9d53f1105b16d34479648bc2c5a42a1356)
+++ app/src/main/java/com/keylesspalace/tusky/fragment/NotificationsFragment.java	(date 1552238948000)
@@ -215,17 +215,21 @@
         adapter.setUseAbsoluteTime(useAbsoluteTime);
         recyclerView.setAdapter(adapter);
 
-        notifications.clear();
         topLoading = false;
         bottomLoading = false;
         bottomId = null;
 
+
+        if (notifications.isEmpty()) {
+            sendFetchNotificationsRequest(null, null, FetchEnd.BOTTOM, -1);
+        } else {
+            progressBar.setVisibility(View.GONE);
+        }
+
         ((SimpleItemAnimator) recyclerView.getItemAnimator()).setSupportsChangeAnimations(false);
 
         updateAdapter();
 
-        sendFetchNotificationsRequest(null, null, FetchEnd.BOTTOM, -1);
-
         return rootView;
     }
```

**Comment by connyduck** [comment]
thx, its  better this way

**Comment by charlag** [comment]
You don't `updateAdapter()`. Works fine?

**Comment by connyduck** [comment]
yes, works fine. But lets put it in to be sure 😅

**Pull request merged**
