### PR TITLE
load filters before anything else

### PR DESCRIPTION
**Pull request by connyduck**
Calling `invalidate` on the room paging source too early apparently stops it from refreshing stuff from network, so let's try this?

### CODE REVIEW

**Comment by charlag** [comment]
I think I tried something like this before, I think it's a bad idea tbh. It means no cached content would be displayed until filters right? Maybe after we could check that whether there was already something emitted and only then invalidate?

**Comment by connyduck** [comment]
That could work as well. I'll try.

**Comment by digitalcircuit** [comment]
Low priority note responding to @charlag's remark:
If filters are to be applied to cached posts after filters load, I'd suggest adding caching filters to the roadmap to minimize the likelihood of showing filtered posts.

My Home timeline is reasonably slow, and I've often had filtered posts show for long enough (before filters loaded) that I could skim the post text/photo, making filters not as useful for avoiding being reminded of emotionally difficult matters.

Pardon if this is out of place - I'd be happy to file a new issue or such if desired.  This happened before the recent filter breakage, I merely kept forgetting to file an issue when I had the energy (I was usually winding down when the problem happened).

**Comment by charlag** [comment]
@digitalcircuit it's alright, we said the same thing on Matrix and I also mentioned in in the [commit](https://github.com/tuskyapp/Tusky/pull/2566/commits/dc47d03b316938fb6077d18fe401701125f86d7f) for the [original PR](https://github.com/tuskyapp/Tusky/pull/2566)

**Comment by connyduck** [comment]
I tried only invalidating when data is already displayed, but it does not work. AndroidX paging is really bad for such things. The only way to get the load state is with a load state listener and that requires an adapter, so no way to do that in the ViewModel. 😢 
Any other ideas? Or should I try routing the load state from the Fragment to the ViewModel? @charlag

**Pull request closed without merging**
