### PR TITLE
Isolate usernames when formatting, to improve interaction of RTL usernames with LTR locales (and vice versa)

### PR DESCRIPTION
**Pull request by Tak**
Fixes notification display when display name contains RTL text, redux :duck: 

Before
image

After
image

### CODE REVIEW

**Comment by connyduck** [comment]
Oh very nice, I did not know about BidiFormatter before.

Can you fix this for system notifications as well? should be in `NotificationHelper` line 495, `joinNames` and `titleForType` methods.

`BidiFormatter.getInstance()` seems to create a new Object everytime it is called, I think it is a good idea to cache the instance in an static field.

**Comment by charlag** [comment]
Wow, cool find!
I'd maybe inject it or save it just as instance field, but maybe not static. It may impose difficulties when changing the language or when testing. Luckily it's part of the support lib and not the system itself so it won't bark during testing.

**Comment by Tak** [comment]
Hm, maybe it makes more sense to wrap the `displayName` getter on `Account`?

**Comment by charlag** [comment]
I'm not sure, it's more of a view concern than data

**Pull request merged**
