### PR TITLE
Add persian language

### PR DESCRIPTION
**Pull request by herotux**

### CODE REVIEW

**Comment by herotux** [comment]
Nobody here?

**Comment by connyduck** [comment]
Can you please format the file so each string is on its own line?

**Comment by connyduck** [comment]
Tests are failing because of
`Error: Found item String/pref_status_text_size more than one time`

**Comment by herotux** [comment]
ok i fix lines but tests are failing and i cant solve them

**Comment by connyduck** [comment]
It failed because of an internal error now.
Thx again!

**Comment by herotux** [comment]
Thanks alot :rose:

**Pull request merged**
