### PR TITLE
fix deleted status reappearing in the timeline

### PR DESCRIPTION
**Pull request by connyduck**
Steps to reproduce: Have a deleted status as the second status in you timeline. Switch accounts (or restart Tusky), notice how it disappears when the timeline is reloaded. Switch again, the toot appears and disappears again.

This PR fixes the problem by deleting the whole range of loaded status instead of only relying on `onConflict = REPLACE`
Not 100% sure this is the correct approach, but it seems to work. Will do more testing tomorrow.

this is part 1/x of fixes to the timeline glitches

### CODE REVIEW

**Comment by charlag** [comment]
Looks good bug I would propose to remove and insert in one transaction. That's probably not terribly important tho.
Also I think that test is a must here, maybe very simple one with two statuses outside the range and one inside.

**Comment by connyduck** [comment]
Whats the best way to get this into a transaction? I tried adding a method to TimelineDao, but then it looses its testability :/

**Comment by charlag** [comment]
Maybe it makes sense to add it to that method which inserts into timeline and test them together? I don't know. Maybe it's also okay to leave it like that, that's not going to reduce consistency.

**Comment by connyduck** [comment]
I will merge it so we can see how it works for users, if there are problems we can change it again.

**Pull request merged**
