### PR TITLE
Fix crash on empty status messages

### PR DESCRIPTION
**Pull request by charlag**

### CODE REVIEW

**Comment by connyduck** [comment]
`LENGTH_DEFAULT` should be a Double so we are not doing Integer division. Now the left hand side of the comparison can only give zero, one, ... and never a fraction like 0.8

**Comment by charlag** [comment]
I don't think it should be double, it should be casted when needed I think

**Comment by charlag** [comment]
Updated with cast to float

**Comment by connyduck** [comment]
thx <3

**Pull request merged**
