### PR TITLE
New Dutch Translation

### PR DESCRIPTION
**Pull request by littlebelgianwriter**
I replaced the old and incomplete translation by my new translation.

### CODE REVIEW

**Comment by charlag** [comment]
Neat, so we can close previous pull request?

**Comment by littlebelgianwriter** [comment]
I hope so, for some reason, I see now the 'All checks have failed message here above.

**Comment by connyduck** [comment]
Looks like the `</resources>` tag at the start of the file is missing

**Comment by charlag** [comment]
I've tried to fix it directly on GitHub, let's see how it goes

**Comment by littlebelgianwriter** [comment]
Thank you! I shouldn't have missed that.

**Comment by connyduck** [comment]
Thank you very much! Your changes will be in the next release!

**Pull request merged**
