### PR TITLE
WIP: First draft of OCR image captions

### PR DESCRIPTION
**Pull request by Tak**
This is a quick hack-in of autosuggesting image captions using Tesseract OCR (specifically [tess-two](https://github.com/alexcohn/tess-two))

~~Right now, it's hardcoded to english, and requires that you have [training data](https://github.com/tesseract-ocr/tessdata/blob/3.04.00/eng.traineddata) stored on the device at `/storage/emulated/0/Android/data/com.keylesspalace.tusky/files/OCR/tessdata/`~~

### CODE REVIEW

**Comment by charlag** [comment]
Cool!
Questions:
can we download training data at runtime?
we can let a user pick a language too
I think there should be just a button to initiate all of that. I like how it's in Pinafore/vanilla web client. How do they detect language btw?

**Comment by a1batross** [comment]
How much APK increase by Tesseract libraries? It's important to include libraries at least for x86, armeabi-v7a and aarch64.

**Comment by Tak** [comment]
Yes, the data just needs to be there before we (re)initialize our tesseract instance.
The training data sets are ~5-50MB in size (English is 20, most European languages are 5-15, simplified Chinese is 40).
I was thinking we could use a similar UI to the one we have for downloading emoji packs.
You have to manually specify the set of languages you want it to support at initialization time. I didn't look into how it selects between specified languages - I presumed it just picks the best match, but 🤷‍♂ 

The size of my debug apk was 23MB (I didn't put training data into the apk), but I'm not sure what architectures are included in that by default.

**Comment by charlag** [comment]
Thanks for details. It all sounds good expect for the APK size IMO - 23 mb is *ooof*
It would be nice if there was non-native build of that because we don't always need top performance, like even TesseractJS has acceptable performance for most use-cases.

**Comment by a1batross** [comment]
The thing is TesseractJS is emscripten port of original C++ library. You can't compile C++ code into JVM or DEX bytecode yet. :(

>I'm not sure what architectures are included in that by default.

You can open APK with any archiver and look what's inside of `lib` folder. 

Anyway, it's very cool feature.

**Comment by Tak** [comment]
This one's not going anywhere, may as well close it

**Pull request closed without merging**
