### PR TITLE
Refresh message timestamp every minute

### PR DESCRIPTION
**Pull request by pandasoft0**
tuskyapp/Tusky#452

This pull request doesn't add the "update a timestamp" on refresh, but it adds "update timestamp" every minute.
The main idea is to send the notifyItemRangeChanged to the adapter with a payload.
Viewholder checks if payload exists and if so - it updates only the fields specified at the payload (creation timestamp for now). If payloads are empty - adapter works just like before.

### CODE REVIEW

**Comment by charlag** [comment]
Hey
Sorry for not reacting to it so far. I briefly looked at the code and I have some design questions. Proposed solution looks like a hack to me tbh. Contents didn't change but we want to update views. Adapter shouldn't be concerned about that (more, we use diffing mechanisms and I wouldn't go around them).
I would rather start a timer in each ViewHolder on bind and stop it on rebind/unmount. Because there are only so many `ViewHolder` (around 10-20 I would say) it shouldn't be a big problem.
Maybe even better than that, there may be some global timer to which they could subscribe/unsubscribe to update simultaneously when the signal is sent.
I would love to hear from others, e.g. @connyduck @Tak

**Comment by Tak** [comment]
I agree with @charlag's analysis

**Comment by connyduck** [comment]
I think starting the timers should be in the Fragments because Fragments have lifecycles and the timers need to be stopped. But also we should not be going around the differ. What about just sending the same list to the differ and the differ dispatches the payload?

**Comment by pandasoft0** [comment]
@connyduck I've updated the logic. Now, interval observable calls the updateAdapter method every minute. Diff callback always retruns the "false" on areContentTheSame, but at the getPayload it compare old item with new and if they are equal - returns only payload with update timestamp. If items are different - returns null. It means the full refresh the view. I added some comments to to the code to explain this logic.

**Comment by charlag** [comment]
I don't ask to change anything yet, but my opinion is that it still breaks some of the diffing. It will force adapter to update all contents and generally do more work than necessarily. I think adapter might create some timer and pass it to `ViewHolder`s so that they can redraw or something like that.

**Comment by pandasoft0** [comment]
@charlag this is a very simple solution. It works over your code and doesn't change the logic of the adapter or the differ. Could you provide an example when updated code refresh all content instead of change timestamps for the same content? I don't see a sense to pass any timer to the adapter or view holders. It may cause a memory or resource leaks. If you think, that provide solution is bad - just close the pull request and i will not create it again, but i will be very grateful if you send me a link to your solution when you fix this issue.

**Comment by charlag** [comment]
@pandasoft0 hey, I'm sorry if I sound too harsh. I just introduced many bugs in timelines and I'm very cautious. I'm very grateful that you're trying to solve this. Please don't take it personally. I'm not a maintainer and I wouldn't close anything even then.
Such an example would be boost/fav of a status which would change all viewHolders instead of just one. Same goes for adding/removing items. We disabled update animation of individuals items, we may enable it again to see what's changing. Maybe there are more cases but I cannot remember any. It's not critical of course but kinda defeats the point of the differ.

**Comment by pandasoft0** [comment]
@charlag My solution uses the old ** deepEquals** method. But i moved call of this function from the **areContentsTheSame** to the **getChangePayload** method. If content of items are the same - it updates the timestamp only, if content of items differ - it returns null as a payload and viewholder refreshes all content.

**Comment by charlag** [comment]
Ah. my apologies! I somehow completely missed that it's part of the `ItemCallback`. It's pretty elegant actually.
I think we can dismiss my abstract concerns.
Sorry again.

**Pull request merged**
