### PR TITLE
Add CI workflow to separate out test and build

### PR DESCRIPTION
**Pull request by technomancy**
As discussed in [this thread](https://birb.site/@charlag/99995654725177209)

Is that what you had in mind?

### CODE REVIEW

**Comment by charlag** [comment]
I think this is it, thanks a lot!
But for some reason Circle doesn't detect this branch now?

**Comment by technomancy** [comment]
There's a setting to build PRs which come from forks (vs just PRs from the same repo) that you might need to turn on within CircleCI; it's off by default for security reasons. Check under "build settings > advanced settings"

**Comment by charlag** [comment]
Yes, this is true put check for example this PR
https://github.com/tuskyapp/Tusky/pull/641

it builds and it comes from another repo (sorry for being unclear)

**Comment by charlag** [comment]
I double checked it and "Build forked pull requests" is selected so either Circle won't change workflow from forks or there's something wrong with config.yml

**Comment by charlag** [comment]
screenshot from 2018-05-11 00-29-46
screenshot from 2018-05-11 00-29-52
okay, there's something...
"We weren't able to start this workflow.
The following jobs are unreachable: build
For more examples see the Workflows documentation."

**Comment by charlag** [comment]
I suspect that's because of the
```
     - build:
         requires:
           - build
```
I'm not sure but you probably meant `test` instead of the second `build`?

**Comment by technomancy** [comment]
Haha; oops. Made a last-minute change and didn't update consistently; my bad.

**Comment by charlag** [comment]
I am just not really familiar with this and I wasn't sure that what I was saying makes sense, thanks!

**Comment by charlag** [comment]
Would you mind if me or you removed only-master filter? this way it will trigger it for this branch. I think I would prefer it to build APKs for forks as well

**Comment by technomancy** [comment]
Do you think it's a good idea to have untrusted APKs mixed in with the ones from the official master branch?

**Comment by charlag** [comment]
Well these are not release builds anyway (not going to be signed with release key) - they're just needed to quickly test PRs. We have no plans to deploy and distribute from the CI for now, it's all testing

**Comment by charlag** [comment]
I wasn't sure how to merge our 2 PRs properly so I merged this one into #639, hope you don't mind.
Thank you a lot for your help, it works as intended!

**Comment by technomancy** [comment]
I see; that sounds reasonable. Glad I could help.

**Pull request closed without merging**
