### PR TITLE
Use HOME as the default tab if it's not recognised

### PR DESCRIPTION
**Pull request by nikclayton**

### CODE REVIEW

**Comment by nikclayton** [comment]
Discovered this when I was checking the PR to add the trending tab, then switched to another branch to work on something else. The code on the other branch tried to restore the trending tab (which didn't exist) and promptly crashed.

**Comment by nikclayton** [comment]
Note that this will add a **second** HOME tab in the situation above. This is something only developers should encounter, so I think that bit of UI oddness is OK.

**Comment by connyduck** [comment]
No, it really should crash in this case. The app is in an invalid state, its a major bug if that would happen, I want to notice it immediately. Showing another tab would hide the problem and lead to more problems down the line (two homes operating on the same cache, I'm not sure that works).

**Comment by connyduck** [comment]
o_0 that should not be possible and should be fixed, yes

**Pull request closed without merging**
