### PR TITLE
remove CircularImageView, use Picasso transformations instead

### LINKED ISSUE #700: Remove CircularImageView
- library is no longer maintained
- I would prefer if avatars were consistently square with rounded corners

### PR DESCRIPTION
**Pull request by connyduck**
closes #700 
looks way better if all avatars have the same shape imho

### CODE REVIEW

**Comment by charlag** [comment]
Using view is *much* cheaper.
If you want, we can make a view which will cut them like that.

**Comment by connyduck** [comment]
You are right 🤔
This was just the fastest thing to do.
Lets make such a view and throw out both `CircularImageView` and `RoundedTransformation`.
Do you want to do this or should I?

**Comment by charlag** [comment]
I can try it out I guess. If I fail to do it today you can pick it up.
-- 
Sincerely,
Ivan



28 Jul 2018, 15:37 by notifications@github.com:

**Comment by connyduck** [comment]
thx

**Pull request closed without merging**
