### PR TITLE
Added Danish translations

### PR DESCRIPTION
**Pull request by Saederup92**

### CODE REVIEW

**Comment by connyduck** [comment]
Some strings are still in English? I would prefer a complete translation.

**Comment by Saederup92** [comment]
I'll update the translations when I've finished them

**Comment by mal0ki** [comment]
@Saederup92 How's this been coming along?

**Comment by Saederup92** [comment]
@mal0ki Nearly forgot about this. Been doing other things for a while

**Comment by charlag** [comment]
@Saederup92 do you mind if we'll close this for now and reopen when it's done?

**Comment by Saederup92** [comment]
It can be closed for now

**Pull request closed without merging**
