### PR TITLE
Changed CheckboxPreference to SwitchPreference

### PR DESCRIPTION
**Pull request by MasterGroosha**
So that long lines show properly.

### CODE REVIEW

**Comment by connyduck** [comment]
closes https://github.com/tuskyapp/Tusky/issues/308

**Comment by connyduck** [comment]
Awesome, thx!

**Comment by connyduck** [comment]
whoops no its `SwitchPreferencerence` there is a `rence` too much 🙈

**Comment by MasterGroosha** [comment]
Damn, I changed CheckboxPreference to SwitchPreference, fucked up with git branches, created a new one and fucked up renaming! 

My bad, will fix in no time with new PR, sorry!

**Comment by MasterGroosha** [comment]
Fixed in #1046

**Pull request merged**
