### PR TITLE
Support a swipe down to dismiss video

### PR DESCRIPTION
**Pull request by nikclayton**
Images can already be dismissed with a swipe, this adds the same functionality to videos.

- Add a VideoActionsListener interface for the hosting activity to dismiss the fragment
- Add a gesture listener for swipes
- Dismiss the fragment if a swipe has a greater Y component than X
- Provide UI feedback by scaling the video viewer as the user swipes

Fixes https://github.com/tuskyapp/Tusky/issues/2833

### CODE REVIEW

**Comment by connyduck** [comment]
Very good idea, but this code makes no difference for me though :/

**Comment by nikclayton** [comment]
Huh. Have you got a link to a status with media it doesn't work on? Works for me on the emulator and Pixel 4a.

**Comment by babogoos** [comment]
I test your version, and it is work for me.
But `SimpleOnGestureListener.onFling()` only invoke when the touch track is quite vertical.
Maybe you can use `SimpleOnGestureListener.onScroll()` and calculate the slope ratio of touch track with `distanceX` and `distanceY`.

**Comment by nikclayton** [comment]
You could, but then the calculation would be different from the swipe-down-to-dismiss calculation in ViewImageFragment, and I imagine that both gestures should be identical.

**Comment by connyduck** [comment]
> Huh. Have you got a link to a status with media it doesn't work on? Works for me on the emulator and Pixel 4a.

I tried again and I think I figured it out, it only works when starting the swipe on the black background, and I was trying on a vertical video that filled the whole frame.

**Comment by nikclayton** [comment]
> > Huh. Have you got a link to a status with media it doesn't work on? Works for me on the emulator and Pixel 4a.
> 
> I tried again and I think I figured it out, it only works when starting the swipe on the black background, and I was trying on a vertical video that filled the whole frame.

I can't reproduce that.

I just tried with the full screen video in https://aus.social/@Godfrey642/109449267279590400, playing full screen, and swiping up/down (where the swipe stays entirely within the video, and never touches any black background) dismisses it as expected.

**Pull request merged**
